### PR TITLE
Added custom scrollbar

### PR DESCRIPTION
**Pull request by SaranshBangar**
Resolves issue #58 

Description -> Added a custom scroll bar in Frontend > src > index.css

Earlier ->

image

### CODE REVIEW

**Comment by SaranshBangar** [comment]
Resolves issue #58

**Comment by subharthihazra** [comment]
Use this colors
webkit-scrollbar-track ->  rgb(230 230 230);
webkit-scrollbar-thumb -> rgb(120 130 140);

**Comment by SaranshBangar** [comment]
@subharthihazra sir, I have updated the colours to resolve issue #58

**Comment by afeefuddin** [comment]
Squash all the commits

**Comment by SaranshBangar** [comment]
@subharthihazra Sorry to disturb you sir, but can please add proper labels on this PR as it would affect my final scores

**Pull request merged**
