### PR TITLE
Add copy text option 

### PR DESCRIPTION
**Pull request by panam1916**
Issue #110 

Add Copy otion on text generated by ai

### CODE REVIEW

**Comment by panam1916** [comment]
is there something wrong in this?

**Comment by afeefuddin** [comment]
The copy button is visible before we get the response. It would be nice if we hide that until the response is completed.

**Comment by panam1916** [comment]
> The copy button is visible before we get the response. It would be nice if we hide that until the response is completed.

ok, i do work on it else text successfully copied or not?

**Comment by afeefuddin** [comment]
LGTM. Merged, thanks @panam1916

**Comment by panam1916** [comment]
Can you Please Assign label for this?

**Comment by panam1916** [comment]
Thanks..!

**Pull request merged**
