### PR TITLE
card layout

### PR DESCRIPTION
**Pull request by Sailesh3000**
I have added the card layout for login and singup for this issue #79

### CODE REVIEW

**Comment by afeefuddin** [comment]
Login page is not even working. Check Preview.

**Comment by subharthihazra** [comment]
@Sailesh3000 please address the issue and create a new PR

**Comment by Sailesh3000** [comment]
is it compulsory to set up firebase to work on the project

**Comment by subharthihazra** [comment]
on your local, what suits you, but in prod it should be properly functioning

**Comment by subharthihazra** [comment]
btw, why there is 0 file change in the PR?

**Pull request closed without merging**
