### PR TITLE
#56 issue (Need of Voice Prompt) resolved

### LINKED ISSUE #56: Need of Voice Prompt
I feel that it would be much better if there would be an option to speak and then the response text would be generated as well i.e. both text and speech prompt. I would like to work upon this issue.

### PR DESCRIPTION
**Pull request by Swastik19Nit**
#56 issue resolved. Voice prompt is added to it.

### CODE REVIEW

**Comment by Swastik19Nit** [comment]
image

**Comment by algovengers** [comment]
Great work!

**Comment by subharthihazra** [comment]
In chat, the response is being parsed empty. plz look into that and create a fresh PR.
Screenshot from 2024-05-14 22-42-49

**Comment by Swastik19Nit** [comment]
Is the response being parsed empty for text prompt or audio prompt as well or both ? This is will help me in proceeding further and take changes accordingly.

**Comment by subharthihazra** [comment]
Yeah both.

**Pull request merged**
