### PR TITLE
Added custom scrollbar

### PR DESCRIPTION
**Pull request by SaranshBangar**
Resolves issue #58 

Description -> Added a custom scroll bar in Frontend > src > index.css

### CODE REVIEW

**Comment by SaranshBangar** [comment]
Resolves issue #58

**Comment by subharthihazra** [comment]
@SaranshBangar change the color to a grayish one. The orange one is not matching.

**Comment by SaranshBangar** [comment]
@subharthihazra Understood sir, please give me a few mins to update the branch

**Comment by algovengers** [comment]
no issues, take your time, and please add a screenshot of it.

**Comment by subharthihazra** [comment]
please also add a screenshot of your change.

**Comment by SaranshBangar** [comment]
Raised a new PR due to complications #76

**Pull request closed without merging**
